apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fuse-csi-driver
  namespace: fuse-csi-system
spec:
  template:
    spec:
      containers:
        - name: fuse-csi-driver
          image: ghcr.io/tak-55/fuse_k8s-fuse-csi-driver:latest
          imagePullPolicy: Always
        - name: node-driver-registrar
          securityContext:
            runAsNonRoot: false
