apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../csi/fuse-csi-driver.yaml
  - ../../csi/fuse-csi-driver-daemonset-prod.yaml
  - ../../sshfs/deploy.yaml
  - ../../s3fs/deploy.yaml
patches:
  - path: csi-patch.yaml
  - path: sshfs-patch.yaml
  - path: s3fs-patch.yaml
