apiVersion: v1
kind: Pod
metadata:
  name: s3fs-example
spec:
  volumes:
    - name: s3fs-vol
      csi:
        volumeAttributes:
          bucket: example-bucket
          endpoint: https://s3.amazonaws.com
          region: us-east-1
          noCheckCert: "false"
