apiVersion: v1
kind: Pod
metadata:
  name: s3fs-fdpass-example
spec:
  volumes:
    - name: s3fs-vol
      csi:
        volumeAttributes:
          bucket: example-bucket
          endpoint: https://minio.example.com:9000
          region: us-east-1
          noCheckCert: "false"
