apiVersion: v1
kind: Pod
metadata:
  name: sshfs-fdpass-example
spec:
  volumes:
    - name: sshfs-vol
      csi:
        volumeAttributes:
          host: example-ssh.example.com
          user: example-user
          remotePath: /data
          port: "22"
          strictHostKeyCheck: "true"
